id: P008135
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16702
  title: ས་སྲོས་ཀྱི་འཆར་སྒོ།
  author: ''
  volumes:
    13cc5504fcc34770a8ce211a581bb7e3:
      image_group_id: I2PD18257
      title: ''
      volume_number: 1
      total_pages: 306
ebook_metadata:
  title: ས་སྲོས་ཀྱི་འཆར་སྒོ།
  author: ''
  sku: P008135
  cover: cover.jpg
  layers:
  - pagination
