id: opecha:P008135
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16702
  title: ས་སྲོས་ཀྱི་འཆར་སྒོ།
  volume:
    0997d79c67a34429a2569695a6aee8e2:
      image_group_id: I2PD18257
      title: Volume 1 of sa sros kyi 'char sgo/
      volume_number: 1
      total_pages: 306
  author: ''
ebook_metadata:
  title: ས་སྲོས་ཀྱི་འཆར་སྒོ།
  author: ''
  sku: P008135
  cover: cover.jpg
  layers:
  - pagination
